version: '3'

tasks:
  hpack:
    cmds:
      - hpack -f
    sources:
      - ./src/*
      - package.yaml
    generates:
      - ./*.cabal

  stack2cabal:
    cmds:
      - stack2cabal --no-run-hpack
    sources:
      - stack.yaml
    generates:
      - cabal.project
      - cabal.project.freeze

  stack2cabal-8.10.7:
    cmds:
      - stack2cabal --no-run-hpack -f stack-ghc-8.10.7.yaml
    sources:
      - stack-ghc-8.10.7.yaml
    generates:
      - cabal.project
      - cabal.project.freeze

  stack2cabal-9.0.2:
    cmds:
      - stack2cabal --no-run-hpack -f stack-ghc-9.0.2.yaml
    sources:
      - stack-ghc-9.0.2.yaml
    generates:
      - cabal.project
      - cabal.project.freeze

  stack2cabal-9.2.5:
    cmds:
      - stack2cabal --no-run-hpack -f stack-ghc-9.2.5.yaml
    sources:
      - stack-ghc-9.2.5.yaml
    generates:
      - cabal.project
      - cabal.project.freeze

  autogen:
    deps: [stack2cabal,hpack]

  build:
    deps: [autogen]
    cmds:
      - cabal build -O0 {{.CLI_ARGS}}

  repl:
    deps: [autogen]
    cmds:
      - cabal repl -O0 {{.CLI_ARGS}}

  test:
    deps: [autogen]
    cmds:
      - cabal test -O0 {{.CLI_ARGS}}