version: '3'

includes:
  hs:
    taskfile: Taskfile-haskell.yml
    vars:
      LTS: '{{.LTS | default "20.11"}}'
      GLOBAL_FLAGS: '{{.GLOBAL_FLAGS | default "--store-dir=$HOME/.cabal/nix/store"}}'
